version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/assignment
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
      - /data/configdb
    ports:
      - 27017:27017